### ISSUE TITLE
MSI package

### ISSUE THREAD

**Issue by wireks** [Ylianst/MeshAgent#217]
Is it possible to create MSI package of MeshAgent for deployment via GPO ?

**Comment by Martin900t** [comment]
I've pushed the exe and installed via command c:\meshagent64-Patrons -install .

**Comment by si458** [comment]
you can create your own msi package with something like 'advanced installer' include the exe and then 
tell the msi to run the command `meshagent64-mymeshgroup.exe -fullinstall`
note, the end user MIGHT still see a pop up black window, but its better than nothing!
